sudo: required
services:
  - docker

before_install:
  - docker build -t roelfie/react-app -f Dockerfile.dev .

# Tell Create React App / Jest to run tests once and exit (instead of showing the interactive CLI).
script:
  - docker run -e CI=true roelfie/react-app npm run test

# The following AWS elasticbeanstalk configuration assumes that there already is
# a beanstalk application of type docker created in AWS.
# By cloning the git repo into the appropriate S3 bucket, beanstalk will automatically 'docker build' & deploy it.
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket-name: "elasticbeanstalk-eu-west-3-837063707632"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


