sudo: required
services:
  - docker

before_install:
  - docker build -t roelfie/react-app -f Dockerfile.dev .

# Tell Create React App / Jest to run tests once and exit (instead of showing the interactive CLI).
script:
  - docker run -e CI=true roelfie/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket-name: "elasticbeanstalk-eu-west-3-837063707632"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


